homeassistant: true
advanced:
  network_key:
    - 157
    - 215
    - 140
    - 31
    - 71
    - 111
    - 39
    - 70
    - 26
    - 173
    - 48
    - 39
    - 234
    - 143
    - 167
    - 39
  pan_id: 23124
  ext_pan_id:
    - 48
    - 145
    - 174
    - 1
    - 101
    - 29
    - 166
    - 141
mqtt:
  server: mqtt://core-mosquitto
  user: mqtt-user
  password: mqttpassword
serial:
  port: /dev/ttyACM0
  adapter: deconz
frontend:
  port: 8099
devices:
  '0x60a423fffe0250be':
    friendly_name: Desk light
  '0xa4c138e413b5e4ee':
    friendly_name: Bedroom main light
  '0x00124b00226a386e':
    friendly_name: Bathroom moisture sensor
  '0x90fd9ffffe20d266':
    friendly_name: Bathroom light
  '0xcc86ecfffeb79b48':
    friendly_name: Bedroom corner light
  '0xa4c138565c96fb40':
    friendly_name: Corner light
  '0xa4c1382655c1b1bc':
    friendly_name: Mood light
  '0x00124b0023a4f561':
    friendly_name: Kitchen light
    color_sync: true
    state_action: false
  '0xa4c138294524063d':
    friendly_name: Table light
  '0x00124b0021149c0a':
    friendly_name: Couch floor light
  '0x001788010b77bc9c':
    friendly_name: Living room button
  '0x001788010b5962cd':
    friendly_name: Bedroom button
  '0x001788010bf6b616':
    friendly_name: Living room main
  '0x00158d0007e0c2ec':
    friendly_name: Bedroom window sensor
  '0x00158d00094348ca':
    friendly_name: Pillbox sensor
  '0x00158d0007e02bc8':
    friendly_name: Living room window sensor
  '0x00158d00094348e1':
    friendly_name: Smoking sensor
  '0x90fd9ffffee5f341':
    friendly_name: Bedroom corner button
  '0x00124b0021f08e30':
    friendly_name: TV floor light
  '0x00158d0006726dde':
    friendly_name: Desk light button
  '0x842e14fffedb9494':
    friendly_name: Toast maker
  '0x00124b0023973624':
    friendly_name: Toast maker button
  '0x001788010d289190':
    friendly_name: Washer waiter button
  '0xa4c13857adc6a6ca':
    friendly_name: Hall light
  '0xec1bbdfffedf77b6':
    friendly_name: Hall motion sensor
  '0xbc33acfffed7cb7e':
    friendly_name: Bathroom motion sensor
  '0x00158d0008c97426':
    friendly_name: Litterbox sensor
  '0x00124b0023973630':
    friendly_name: Table button
  '0xa4c138c5547b6d8d':
    friendly_name: Computer light
  '0xa4c13878cecb333f':
    friendly_name: Downstairs washer
  '0xa4c13834b9e85342':
    friendly_name: Dryer
  '0xa4c1385a4bc70414':
    friendly_name: Upstairs washer
  '0x00124b001b78b869':
    friendly_name: Bathroom fan
  '0x00158d0009698205':
    friendly_name: Front door sensor
groups:
  '1':
    friendly_name: Living room floor light
    devices:
      - 0x00124b0023a4f561/11
      - 0x00124b0021f08e30/11
      - 0x00124b0021149c0a/11
  '2':
    friendly_name: All lights
    devices:
      - 0x90fd9ffffe20d266/1
      - 0xcc86ecfffeb79b48/11
      - 0xa4c138e413b5e4ee/11
      - 0xa4c138565c96fb40/11
      - 0x00124b0021149c0a/11
      - 0x60a423fffe0250be/11
      - 0xa4c13857adc6a6ca/11
      - 0x001788010bf6b616/11
      - 0xa4c1382655c1b1bc/11
      - 0xa4c138294524063d/11
      - 0x00124b0021f08e30/11
      - 0x00124b0023a4f561/11
      - 0x00124b0023a4f561/15
  '3':
    friendly_name: Living room lights
    devices:
      - 0xa4c138565c96fb40/11
      - 0x00124b0021149c0a/11
      - 0x00124b0023a4f561/11
      - 0x001788010bf6b616/11
      - 0xa4c1382655c1b1bc/11
      - 0xa4c138294524063d/11
      - 0x00124b0021f08e30/11
